# Generated by Django 5.0.1 on 2024-01-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_image1_news_image2_news_image3_news_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=23, upload_to='media/'),
            preserve_default=False,
        ),
    ]
